# Docker Compose란? 서로 다른 컨테이너들끼리 연동할 수 있게끔 만들어주는 역할을 수행한다.

version: "3" #docker compose version
services: #docker compose가 실행해야 할 것들
  redis-server: #container 이름
    image: "redis"
  node-app: # container name
    build: . #dockrFile location
    ports:
      - "5000:3000" #local port : container port


#실행 방법 : docker-compose up
#수정이 있다면 : docker-compose up --build
  